# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: ubuntu:16.04

pipelines:
  default:
    - step:
        name: Build
        image: ipmb/ubuntu-python-build:latest
        script:
          - ln -s $BITBUCKET_CLONE_DIR /code
          - mkdir -p _dist
          - /build.sh
          - cp /dist/*.tar.gz _dist/
        artifacts:
          - _dist/*.tar.gz
    - step:
        name: Test
        image: ipmb/ubuntu-python-clean:latest
        script:
          - export SECRET_KEY=secret
          - export ALLOWED_HOSTS='*'
          - export DATABASE_URL=postgres://postgres:secret@localhost:5432/postgres
          - /test.sh _dist/*.tar.gz
          - mkdir test-reports
          - cp /results/junit.xml test-reports/junit.xml
        services:
          - postgres
          
definitions:
  services:
    postgres:
      image: postgres:9.6
      environment:
        POSTGRES_PASSWORD: secret
