image: ubuntu:16.04

pipelines:
  default:
    - step:
        name: Build
        image: ipmb/ubuntu-python-build:latest
        script:
          - /build.sh $BITBUCKET_CLONE_DIR
          - mv /dist _dist
        artifacts:
          - _dist/*.tar.gz
    - step:
        name: Test
        image: ipmb/ubuntu-python-clean:latest
        script:
          - export SECRET_KEY=secret
          - export ALLOWED_HOSTS='*'
          - export DATABASE_URL=postgres://postgres:secret@localhost:5432/postgres
          - /test.sh $BITBUCKET_CLONE_DIR/_dist/*.tar.gz
          - mv /results test-reports
        services:
          - postgres
    - step:
        name: Upload
        image: mesosphere/aws-cli
        script:
          - aws s3 cp _dist/*.tar.gz s3://$S3_PLATTER_BUCKET --no-progress
          
definitions:
  services:
    postgres:
      image: postgres:9.6
      environment:
        POSTGRES_PASSWORD: secret
