FROM ipmb/ubuntu-python-platter:latest as build

ENV LANG C.UTF-8

ADD . /code

RUN /build.sh /code
WORKDIR /code
RUN export VERSION=$(python3 setup.py --version) && \
    export PLATFORM=$(python3 -c "import sysconfig as sc; \
        print('py{}-{}'.format(sc.get_python_version().replace('.', ''), sc.get_platform()))") && \
    pip3 install shiv && \
    shiv -e saltdash:config.django_manage -o /dist/saltdash-${VERSION}-${PLATFORM}.pyz .

FROM ubuntu:18.04
COPY --from=build /dist /dist
# Contains pytest/coverage config
COPY --from=build /code/setup.cfg .
ENV SECRET_KEY=secret
# Trigger shiv to unpack
RUN apt-get update -q && apt-get install -y python3.6 libpython3.6 python3.6-distutils && \
    ln -s /dist/saltdash-*.pyz /bin/saltdash && saltdash help
CMD /bin/saltdash test -- --junitxml=/results/junit.xml
