FROM ipmb/ubuntu-python-platter:latest as build

ENV LANG C.UTF-8

ADD . /code

RUN /build.sh /code

FROM ipmb/ubuntu-python-clean:latest
COPY --from=build /dist /dist
ENV SECRET_KEY=secret
CMD /test.sh /dist/*.tar.gz
